services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "7226:80" # Expose the API on port 7226
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=PieShop;User Id=sa;Password=YourStrong!Password;TrustServerCertificate=True;
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433" # Expose SQL Server's default port
    environment:
      SA_PASSWORD: "YourStrong!Password"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong!Password", "-Q", "SELECT 1"]
      interval: 30s
      retries: 10
      start_period: 60s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
